// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment/payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreatePaymentRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId              int64    `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TotalPrice           float32  `protobuf:"fixed32,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentRequest) Reset()         { *m = CreatePaymentRequest{} }
func (m *CreatePaymentRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentRequest) ProtoMessage()    {}
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{0}
}

func (m *CreatePaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentRequest.Unmarshal(m, b)
}
func (m *CreatePaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentRequest.Merge(m, src)
}
func (m *CreatePaymentRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentRequest.Size(m)
}
func (m *CreatePaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentRequest proto.InternalMessageInfo

func (m *CreatePaymentRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePaymentRequest) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *CreatePaymentRequest) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

type CreatePaymentResponse struct {
	PaymentId            int64    `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	BillId               int64    `protobuf:"varint,2,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentResponse) Reset()         { *m = CreatePaymentResponse{} }
func (m *CreatePaymentResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentResponse) ProtoMessage()    {}
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a39aceed8019db, []int{1}
}

func (m *CreatePaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentResponse.Unmarshal(m, b)
}
func (m *CreatePaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentResponse.Marshal(b, m, deterministic)
}
func (m *CreatePaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentResponse.Merge(m, src)
}
func (m *CreatePaymentResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentResponse.Size(m)
}
func (m *CreatePaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentResponse proto.InternalMessageInfo

func (m *CreatePaymentResponse) GetPaymentId() int64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *CreatePaymentResponse) GetBillId() int64 {
	if m != nil {
		return m.BillId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreatePaymentRequest)(nil), "CreatePaymentRequest")
	proto.RegisterType((*CreatePaymentResponse)(nil), "CreatePaymentResponse")
}

func init() {
	proto.RegisterFile("payment/payment.proto", fileDescriptor_66a39aceed8019db)
}

var fileDescriptor_66a39aceed8019db = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xed, 0x2e, 0xb4, 0x3a, 0xde, 0x82, 0xd5, 0x55, 0x10, 0x97, 0x9e, 0xf6, 0x62, 0x5a,
	0xf4, 0xe4, 0x55, 0x05, 0xe9, 0xc9, 0xa5, 0x47, 0x2f, 0x4b, 0xdb, 0x0c, 0x1a, 0x4c, 0x9b, 0x98,
	0x4c, 0x05, 0xff, 0xbd, 0x24, 0x8d, 0x2c, 0xc8, 0x9e, 0xc2, 0xfb, 0x06, 0xe6, 0x9b, 0x3c, 0xc8,
	0x4d, 0xfb, 0x33, 0xe0, 0x48, 0x65, 0x7c, 0xb9, 0xb1, 0x9a, 0x74, 0xf1, 0x09, 0x67, 0x4f, 0x16,
	0x5b, 0xc2, 0xed, 0x8c, 0x1b, 0xfc, 0x9a, 0xd0, 0x11, 0xbb, 0x80, 0x6c, 0x72, 0x68, 0x77, 0x52,
	0xac, 0x92, 0x75, 0xb2, 0x59, 0x36, 0xa9, 0x8f, 0xb5, 0x60, 0x97, 0x70, 0xac, 0xad, 0x98, 0x27,
	0x8b, 0x30, 0xc9, 0x42, 0xae, 0x05, 0xbb, 0x81, 0x53, 0xd2, 0xd4, 0xaa, 0x9d, 0xb1, 0xb2, 0xc7,
	0xd5, 0x72, 0x9d, 0x6c, 0x16, 0x0d, 0x04, 0xb4, 0xf5, 0xa4, 0x78, 0x85, 0xfc, 0x9f, 0xcc, 0x19,
	0x3d, 0x3a, 0x64, 0xd7, 0x00, 0xf1, 0xac, 0xbd, 0xf0, 0x24, 0x92, 0x5a, 0xf8, 0x63, 0x3a, 0xa9,
	0xd4, 0x5e, 0x99, 0xfa, 0x58, 0x8b, 0xbb, 0x67, 0xc8, 0xe2, 0x2a, 0xf6, 0x00, 0xe9, 0xbc, 0x9b,
	0xe5, 0xfc, 0xd0, 0x8f, 0xae, 0xce, 0xf9, 0x41, 0x77, 0x71, 0xf4, 0x58, 0xbd, 0xf1, 0x77, 0x49,
	0x1f, 0x53, 0xc7, 0x7b, 0x3d, 0x94, 0x2f, 0x38, 0x92, 0xaa, 0xaa, 0x72, 0x90, 0xbd, 0xd5, 0x0e,
	0xed, 0xb7, 0xec, 0xd1, 0xdd, 0x86, 0xb6, 0xfe, 0xba, 0xeb, 0xd2, 0x10, 0xef, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x7c, 0xbe, 0x76, 0x2b, 0x55, 0x01, 0x00, 0x00,
}
